name: elherafyeen
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.15

environment:
  sdk: ">=2.7.0 <3.0.0"
#
dependency_overrides:
  plugin_platform_interface: ^2.0.1
  permission_handler_platform_interface: ^3.6.1
  package_info: ^2.0.2

dependencies:
  platform: ^3.1.0
  path_provider:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  geolocator: ^7.4.0
  #beso for get country Name
  geocoding: ^2.0.4
  #beso
  country_codes: ^2.1.1
  #beso
  country_code_picker: ^2.0.2

  #geolocator: ^6.2.1
  flutter_swiper:
  flutter_image_compress: ^1.0.0
  url_launcher: 6.0.2
  badges:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  bloc:
  syncfusion_flutter_barcodes: ^19.2.62
  flutter_barcode_scanner:
  circular_menu: ^1.2.3
  flutter_simple_rating_bar: ^0.0.3
  flutter_inner_drawer: ^1.0.0+1
  flutter_animated_dialog:
  fab_circular_menu: ^1.0.2
  navigation_action_bar:
    path: './navigation_action_bar'
  video_player:
  flutter_svg:
  map_launcher: ^2.1.1
  rate_my_app:
  bicolor_icon:
  flutter_rating_bar: ^4.0.0
  onesignal_flutter: 2.6.4
  responsive_framework: ^0.1.4
  auto_size_text: ^2.1.0
  google_maps_flutter:
  google_fonts:
  video_thumbnail: ^0.3.3
  fl_chart: ^0.36.3
  shared_preferences:
  giffy_dialog: ^1.8.0
  http: ^0.13.3
  intl:
  fluttertoast: ^8.0.7
  photo_view: ^0.12.0
  modal_progress_hud: ^0.1.3
  flutter_slidable: ^0.6.0
  easy_localization:
  clippy_flutter: ^1.1.1
  image_picker: ^0.8.2
  uni_links: ^0.5.1
  share: ^2.0.4
  image_cropper: ^1.4.1
  new_version: ^0.2.2
  octo_image: ^1.0.0+1
  cached_network_image: ^3.1.0
  firebase_database:
  #permission_handler: ^8.1.4+2
  permission_handler: ^8.2.5
  font_awesome_flutter: ^9.1.0
  pinch_zoom_image_last: ^0.4.1
  package_info: ^2.0.2
  intl_phone_number_input:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - translations/
    - assets/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
